/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.*/

#include <stdio.h>

main(void){
    int fib0=0, fib1=1, fib2=1, fib2_old, fib1_old, sum=0;
    while(1){
        fib2=fib1+fib0;
        fib2_old=fib2;
        fib1_old=fib1;
        fib0=fib1_old;
        fib1=fib2_old;
        if(fib2%2==0&&fib2<4000000)
            sum+=fib2;
        else if(fib2>=4000000)
            break;
    }
    return sum;//display sum
}
